import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-600 text-white p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-2xl font-bold">Docs Builder</Link>
            <ul className="flex space-x-4 items-center">
              <li><Link href="/" className="hover:underline">Home</Link></li>
              {session ? (
                <>
                  <li><Link href="/projects" className="hover:underline">Projects</Link></li>
                  <li>
                    <form action="/api/auth/signout" method="POST">
                      <Button variant="outline" type="submit">Logout</Button>
                    </form>
                  </li>
                </>
              ) : (
                <li>
                  <Link href="/api/auth/signin">
                    <Button variant="outline">Login</Button>
                  </Link>
                </li>
              )}
            </ul>
          </nav>
        </header>
        <main className="container mx-auto mt-8 px-4">
          {children}
        </main>
        <footer className="bg-gray-200 mt-8 py-4">
          <div className="container mx-auto text-center">
            © 2024 Automated Internal Docs Builder
          </div>
        </footer>
      </body>
    </html>
  );
}
